name: 'route_fleet_analytics'
version: '1.0.0'
config-version: 2

profile: 'route_fleet_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  route_fleet_analytics:
    staging:
      +materialized: view
      +schema: SILVER
    intermediate:
      +materialized: table
      +schema: SILVER
    marts:
      +materialized: table
      +schema: GOLD

vars:
  raw_database: FLEET_ANALYTICS
  raw_schema: RAW
